health-check:
  log-path: ./logs
  website-enable : true
  wsdl-enable: true
  nginx-log-enable: true
  nging-log-err-limit: 40
  polling:
    time: 30000
  websites:
    - name: 测试主机1
      url: 127.0.0.1
      port: 8082
    - name: 测试主机2
      url: 127.0.0.1
      port: 8080
    - name: 测试主机3
      url: 121.196.221.138
      port: 22
  nginxlogs:
    - name: 测试主机1
      host: 121.196.221.138
      port: 22
      account: root
      password: Qw880712
      path: /test
  wsdls:
    - name: 测试方法
      url: http://127.0.0.1:8081/WSWorklistQueryManagerServiceBinding?WSDL
      methods:
        - name: queryFourCount
          params:
            - value: 1
              type: String
            - value: 2
              type: String
            - value: bizName
              type: String
        - name: queryPersonFinishedWorkItemsCriteria
          params:
            - value: userID
              type: String
            - value: personID
              type: String
            - value: scope
              type: String
            - value: activityDefID
              type: String
            - value: includeHistory
              type: String
            - value: 10
              type: int
            - value: 100
              type: int
server:
  port: 8082