health-check:
  log-path: ./logs
  polling:
    time: 50000
  websites:
    - name: 测试主机1
      url: 127.0.0.1
      port: 8081
    - name: 测试主机2
      url: 127.0.0.1
      port: 8080
    - name: 测试主机3
      url: 127.0.0.1
      port: 8080