health-check:
  log-path: ./logs
  website-enable : true
  wsdl-enable: false
  nginx-log-enable: false
  nging-log-err-limit: 40
  sms-notification:
    sms-wsdl-path: http://10.24.19.52:8100/EIP/OSB_EIP_EIP_HQ_ImportSmsSrv.v0/proxy/OSB_EIP_EIP_HQ_ImportSmsSrv?wsdl
    sms-enable: false
    sms-method-name: process
    appid: 10344
    templateid: 10344202304171118001
    receiver-number: 17276440520
  polling:
    time: 100000
  websites:
    - name: ERPUAT
      url: 10.24.20.45
      port: 8080
    - name: localhost
      url: 127.0.0.1
      port: 8080
    - name: baidu
      url: 110.242.68.4
      port: 80
  nginxlogs:
    - name: ERPUAT
      host: 10.24.20.47
      port: 22
      authorized: false
      prikey: /home/bps/.ssh/id_rsa
      account: bps
      password: Qw880712
      path: /apps/logs/nginx
      prefix: access_webservice_
  wsdls:
    - name: 测试 WSProcessInstManager
      url: http://192.168.30.103:8080/default/WSProcessInstManagerService
      methods:
        - name: queryProcessInstDetail
          tenantid: CMS
          params:
            - value: sysadmin
              type: String
              name: userID
            - value: 846142
              type: String
              name: processInstID
server:
  port: 8083
  servlet:
    context-path: /health-checker
spring:
  application:
    name: health-checker
  datasource:
    url: jdbc:mysql://172.29.250.129:3306/guard?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useOldAliasMetadataBehavior=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver